<?php

use yii\db\Migration;

/**
 * Class m220315_091723_photo
 */
class m220315_091723_photo extends Migration
{
    /** @var string */
    private $tabel;

    /**
     * @return void
     */
    public function init()
    {
        $this->tabel = 'photo';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable($this->tabel, [
            'id' => $this->primaryKey(10),
            'album_id' => $this->integer(10)->notNull(),
            'title' => $this->string(255)
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable($this->tabel);
    }
}
